const GOOGLEPHOTOURL = "https://photoslibrary.googleapis.com/v1/";
const GOOGLEMIGRATIONAPILOCAL = "http://localhost:3000/";
const GOOGLEMIGRATIONAPIHOSTED = "";

const PAGESIZE = 100;
module.exports = {
    GOOGLEPHOTOURL: GOOGLEPHOTOURL,
    PAGESIZE: PAGESIZE,
    GOOGLEMIGRATIONAPILOCAL: GOOGLEMIGRATIONAPILOCAL,
    GOOGLEMIGRATIONAPIHOSTED: GOOGLEMIGRATIONAPIHOSTED
}