const GOOGLEPHOTOURL = "https://photoslibrary.googleapis.com/v1/";
const GOOGLEMIGRATIONAPILOCAL = "http://localhost:8080/";
const GOOGLEMIGRATIONAPIHOSTED = "https://google-photos-migration.herokuapp.com/";

const PAGESIZE = 100;
module.exports = {
    GOOGLEPHOTOURL: GOOGLEPHOTOURL,
    PAGESIZE: PAGESIZE,
    GOOGLEMIGRATIONAPILOCAL: GOOGLEMIGRATIONAPILOCAL,
    GOOGLEMIGRATIONAPIHOSTED: GOOGLEMIGRATIONAPIHOSTED
}